import { expect, test } from '@playwright/test'

test('real DevTools edits the running app without losing interaction state and restores it', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/demo')
  const action = page.getByRole('button', { name: 'Count 0', exact: true })
  const appearance = () => page.getByTestId('primary-action').evaluate((el) => {
    const css = getComputedStyle(el)
    return { primary: css.getPropertyValue('--ui-primary'), radius: css.borderRadius, font: css.fontFamily }
  })
  await page.getByTitle('Toggle Nuxt DevTools', { exact: true }).waitFor()
  const original = await appearance()
  await action.click()
  await page.getByRole('textbox', { name: 'Search products' }).fill('Desk')
  await page.getByTitle('Toggle Nuxt DevTools', { exact: true }).click()
  const tools = page.frameLocator('iframe[src*="__nuxt_devtools__"]')
  await tools.getByRole('link', { name: 'Get Started', exact: true }).click()
  // DevTools 3 exposes unpinned integrations through its overflow button.
  await tools.locator('button').filter({ hasText: /^\d+$/ }).click()
  await tools.locator('a[href$="/custom-id-theme"]').click()
  const editor = tools.frameLocator('iframe[src$="/__id/theme"]')
  await expect(editor.getByRole('button', { name: 'Reset preview', exact: true })).toBeVisible()
  expect(await appearance()).toEqual(original)
  await editor.getByRole('button', { name: 'Primary', exact: true }).click()
  const start = Date.now()
  await editor.getByRole('button', { name: 'violet', exact: true }).click()
  await expect.poll(async () => (await appearance()).primary).not.toBe(original.primary)
  console.log('DevTools edit-to-observed-style (development, includes browser automation): ' + (Date.now() - start) + 'ms')
  await expect(page.getByRole('button', { name: 'Count 1', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Search products' })).toHaveValue('Desk')
  await editor.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await appearance()).primary).toBe(original.primary)
  await editor.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect.poll(async () => (await appearance()).primary).not.toBe(original.primary)
  await editor.getByRole('button', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await editor.getByRole('tab', { name: 'Styles', exact: true }).click()
  await editor.getByRole('combobox', { name: 'Corner radius', exact: true }).fill('0.5rem')
  await editor.getByRole('option', { name: '0.5rem', exact: true }).click()
  await expect.poll(async () => (await appearance()).radius).not.toBe(original.radius)
  await editor.getByRole('tab', { name: 'Typography', exact: true }).click()
  await editor.getByRole('combobox', { name: 'Body', exact: true }).click()
  await editor.getByRole('option', { name: 'System serif', exact: true }).click()
  await expect.poll(async () => (await appearance()).font).not.toBe(original.font)
  await expect(page.getByRole('textbox', { name: 'Search products' })).toHaveValue('Desk')
  const download = page.waitForEvent('download')
  await editor.getByRole('button', { name: 'Export brand JSON', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('brand.studio.json')
  await editor.getByRole('button', { name: 'Reset preview', exact: true }).click()
  await expect.poll(appearance).toEqual(original)
  await expect(page.getByRole('textbox', { name: 'Search products' })).toHaveValue('Desk')
  await page.screenshot({ path: '.output/tests/devtools-editor.png' })
  await page.getByTitle('Toggle Nuxt DevTools', { exact: true }).click()
  await page.getByRole('link', { name: 'Details', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'App details' })).toBeVisible()
  expect(errors).toEqual([])
})
