import { expect, test } from '@playwright/test'

for (const mode of ['light', 'dark']) test('independent app receives drafts, preserves behavior and bounds navigation: ' + mode, async ({ page }) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/editor?view=external&editor=colors&compare=true&docked=true&mode=' + mode)
  const draft = page.frameLocator('iframe[title="Draft brand preview"]')
  const original = page.frameLocator('iframe[title="Original brand preview"]')
  await expect(draft.locator('html')).toHaveAttribute('data-id-preview', 'ready', { timeout: 120_000 })
  await expect(draft.locator('html')).toHaveClass(new RegExp(mode))
  const color = () => draft.getByRole('button', { name: /Count/ }).evaluate(el => getComputedStyle(el).getPropertyValue('--ui-primary').trim())
  const before = await color()
  await page.getByRole('button', { name: 'Use violet', exact: true }).click()
  await expect.poll(color).not.toBe(before)
  await expect.poll(() => original.getByRole('button', { name: 'Count 0', exact: true }).evaluate(el => getComputedStyle(el).getPropertyValue('--ui-primary').trim())).toBe(before)
  await draft.getByRole('button', { name: 'Count 0', exact: true }).click()
  await expect(draft.getByRole('button', { name: 'Count 1', exact: true })).toBeVisible()
  await draft.getByRole('link', { name: 'Outside preview', exact: true }).click()
  await expect(draft.getByRole('heading', { name: 'Independent app' })).toBeVisible()
  await draft.getByRole('link', { name: 'Details', exact: true }).click()
  await expect(draft.getByRole('heading', { name: 'App details' })).toBeVisible()
  await expect(page).toHaveURL(/path=(%2F|\/)demo(%2F|\/)details/)
  await expect(original.getByRole('heading', { name: 'App details' })).toBeVisible()
  await page.getByRole('button', { name: 'Templates', exact: true }).click()
  const thumbnail = page.locator('iframe[title="Independent app thumbnail"]')
  await thumbnail.scrollIntoViewIfNeeded()
  await expect(thumbnail.locator('..')).toHaveAttribute('data-preview-state', 'ready')
  await expect(page.frameLocator('iframe[title="Independent app thumbnail"]').locator('html')).toHaveClass(new RegExp(mode))
  expect(errors).toEqual([])
})

test('opening the app directly leaves preview inactive', async ({ page }) => {
  await page.goto('http://127.0.0.1:3444/demo')
  await expect(page.getByRole('button', { name: 'Count 0', exact: true })).toBeVisible()
  await expect(page.locator('html')).not.toHaveAttribute('data-id-preview')
  await page.getByRole('link', { name: 'Outside preview', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Outside page' })).toBeVisible()
})
