import { expect, test } from '@playwright/test'

for (const width of [1440, 390]) test('brand showcase separates browsing from authoring at ' + width, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/showcase')
  await expect(page.getByRole('button', { name: 'Toggle host mode' })).toBeEnabled({ timeout: 60000 })
  const showcase = page.locator('[data-studio-showcase]')
  const content = showcase.locator('[data-showcase-components]')
  await expect(content.getByRole('region', { name: 'Interactive component examples' })).toBeVisible()
  await expect(showcase.getByRole('button', { name: 'Export', exact: true })).toHaveCount(0)
  await expect(showcase.getByRole('button', { name: 'Brand picker', exact: true })).toHaveCount(0)
  await expect(showcase.locator('iframe')).toHaveCount(0)
  const pickerBox = (await showcase.getByRole('group', { name: 'Preview type', exact: true }).boundingBox())!
  const contentBox = (await content.boundingBox())!
  expect(pickerBox.y + pickerBox.height).toBeLessThan(contentBox.y)
  expect(await content.evaluate(element => parseFloat(getComputedStyle(element).paddingLeft))).toBe(width < 640 ? 16 : 24)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  const gridBox = (await page.locator('[data-showcase-grid]').boundingBox())!
  expect(contentBox.width).toBeLessThanOrEqual(gridBox.width)
  const email = content.locator('input[type="email"]').first()
  await email.fill('preserved@example.com')
  const expand = showcase.getByRole('button', { name: 'Expand preview', exact: true })
  await expand.click()
  await expect(showcase).toHaveAttribute('aria-modal', 'true')
  await content.getByRole('combobox').first().click()
  await expect(page.locator('[role="listbox"][data-state]')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(showcase).toHaveAttribute('aria-modal', 'true')
  await expect(page.locator('[role="listbox"][data-state]')).toBeHidden()
  await expect(email).toHaveValue('preserved@example.com')
  await page.keyboard.press('Escape')
  await expect(expand).toBeFocused()
  await expect(email).toHaveValue('preserved@example.com')
  await expand.click()
  await showcase.getByRole('combobox', { name: 'Preview', exact: true }).click()
  await page.getByRole('option', { name: 'Landing', exact: true }).click()
  await expect(showcase.locator('[data-preview-state]')).toHaveAttribute('data-preview-state', 'ready', { timeout: 60000 })
  const preview = showcase.frameLocator('iframe[title="Landing template preview"]')
  await expect(preview.getByRole('heading', { name: 'Your projects, in one place' })).toBeVisible()
  const originalFrame = page.frames().find(frame => frame.url().includes('/studio/preview'))!
  await preview.locator('body').click({ position: { x: 10, y: 10 } })
  await page.keyboard.press('Escape')
  await expect(expand).toBeFocused()
  expect(page.frames()).toContain(originalFrame)
  await page.getByRole('button', { name: 'Toggle host mode' }).click()
  await expect(page.locator('html')).toHaveClass(/light/)
  await expect(preview.locator('html')).toHaveClass(/light/)
  // Reopening the picker above an existing iframe must keep choices clickable.
  await showcase.getByRole('button', { name: 'Templates', exact: true }).click()
  const gallery = showcase.getByRole('group', { name: 'Choose a template', exact: true })
  await gallery.getByRole('button', { name: 'Landing', exact: true }).click({ timeout: 5000 })
  await expect(gallery).toBeHidden()
  await showcase.getByRole('button', { name: 'Components', exact: true }).click()
  await expect(email).toHaveValue('preserved@example.com')
  await expect(showcase.getByRole('link', { name: 'Open Studio', exact: true })).toHaveAttribute('href', '/studio?browse=true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
