packages:
  - docs
  - playground
  - templates/*
catalog:
  'nuxt': '^4.5.2'
  '@nuxt/kit': '^4.5.2'
  '@nuxt/schema': '^4.5.2'
  '@nuxt/ui': '^4.11.2'
  'tailwindcss': '^4.3.3'
  'docus': '^5.13.0'
  'typescript': '^6.0.3'
  'vue-tsc': '^3.3.11'
  '@iconify-json/lucide': '^1.2.137'
  '@iconify-json/vscode-icons': '1.2.83'

overrides:
  '@happydesigns/id': workspace:*
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
