import { copyFileSync, cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const distDir = join(rootDir, 'dist')
const tscBin = join(rootDir, 'node_modules', 'typescript', 'bin', 'tsc')

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    stdio: 'inherit',
  })
  if (result.error) {
    console.error(result.error)
    process.exit(1)
  }
  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

function copyRuntimeFiles() {
  cpSync(join(rootDir, 'app'), join(distDir, 'app'), {
    recursive: true,
  })
  const themesDir = join(rootDir, 'themes')
  for (const themeDir of readdirSync(themesDir)) {
    const tokenSource = join(themesDir, themeDir, 'tokens.css')
    if (!existsSync(tokenSource)) {
      continue
    }
    const tokenTarget = join(distDir, 'themes', themeDir, 'tokens.css')
    mkdirSync(dirname(tokenTarget), {
      recursive: true,
    })
    copyFileSync(tokenSource, tokenTarget)
  }
}

function listFiles(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const file = join(dir, entry)
    const stat = statSync(file)
    if (stat.isDirectory()) {
      listFiles(file, files)
    }
    else {
      files.push(file)
    }
  }
  return files
}

rmSync(distDir, {
  force: true,
  recursive: true,
})

const packageManifest = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf8'))
const { catalog } = parse(readFileSync(join(rootDir, 'pnpm-workspace.yaml'), 'utf8'))
const moduleDependencies = Object.fromEntries(['nuxt', '@nuxt/ui'].map((name) => {
  const declared = packageManifest.dependencies[name]
  const version = declared === 'catalog:' ? catalog[name] : declared
  if (!version || version.startsWith('catalog:')) throw new Error('Unresolved module dependency: ' + name)
  return [name, version]
}))
writeFileSync(join(rootDir, 'module-meta.generated.ts'),
  '// Generated by build:package. Do not edit.\nexport const dependencies = '
  + JSON.stringify(moduleDependencies, null, 2) + '\n')
const projectTemplates = {}
for (const variant of ['native', 'guide', 'legacy']) {
  const directory = join(rootDir, 'templates/project', variant)
  projectTemplates[variant] = Object.fromEntries(listFiles(directory).sort().map(file => [
    file.slice(directory.length + 1).replaceAll('\\', '/'), readFileSync(file, 'utf8').replaceAll('\r\n', '\n'),
  ]))
}
// Resolve catalog and workspace references before bundling so browser exports stay self-contained.
for (const files of Object.values(projectTemplates)) {
  const manifest = JSON.parse(files['package.json'])
  for (const group of ['dependencies', 'devDependencies']) {
    for (const [name, version] of Object.entries(manifest[group] ?? {})) {
      if (version === 'workspace:^' && name === packageManifest.name) {
        manifest[group][name] = '^' + packageManifest.version
      }
      else if (version === 'catalog:') {
        if (!catalog[name]) throw new Error('Missing template catalog entry: ' + name)
        if (!packageManifest.dependencies?.[name] && !packageManifest.devDependencies?.[name] && !packageManifest.peerDependencies?.[name]) {
          throw new Error('Template dependency is not declared in the root package: ' + name)
        }
        manifest[group][name] = JSON.parse(readFileSync(join(rootDir, 'node_modules', name, 'package.json'), 'utf8')).version
      }
      else if (version.startsWith('workspace:') || version.startsWith('catalog:')) {
        throw new Error('Unsupported template dependency reference: ' + name + '@' + version)
      }
    }
  }
  files['package.json'] = JSON.stringify(manifest, null, 2) + '\n'
}

writeFileSync(join(rootDir, 'src/project-templates.generated.ts'),
  '// Generated from templates/project by build:package. Do not edit.\n'
  + 'export const projectTemplates: Record<"native" | "guide" | "legacy", Record<string, string>> = '
  + JSON.stringify(projectTemplates, null, 2) + '\n')

run(process.execPath, [tscBin, '-p', 'tsconfig.package.json'])
copyRuntimeFiles()

// This example consumes the public generator; its runtime is not hand-maintained.
const { createStudioDocument, createStudioRuntimeFiles } = await import('../dist/src/studio.js')
const { brandIdentity, brandTheme } = await import('../templates/brand-layer/brand.ts')
const document = createStudioDocument(brandIdentity, brandTheme)
const templateDir = join(rootDir, 'templates/brand-layer')
writeFileSync(join(templateDir, 'brand.studio.json'), JSON.stringify(document, null, 2) + '\n')
for (const [path, contents] of Object.entries(createStudioRuntimeFiles(document, { styles: 'fragment' }))) {
  const target = join(templateDir, path)
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, contents)
}
